export interface KanaSeedItem {
  character: string;
  romaji: string;
  category: 'base' | 'dakuten' | 'handakuten' | 'yoon';
  rowGroup: string;
  mnemonic: string;
  exampleWord: string;
  exampleReading: string;
  exampleMeaning: string;
  orderIndex: number;
}

export const KANA_DATA: KanaSeedItem[] = [
  // --- BASE 46 ---
  // Vowels
  {
    character: 'あ',
    romaji: 'a',
    category: 'base',
    rowGroup: 'vowels',
    mnemonic: 'Looks like an Apple with a stem',
    exampleWord: '朝',
    exampleReading: 'あさ (asa)',
    exampleMeaning: 'morning',
    orderIndex: 1,
  },
  {
    character: 'い',
    romaji: 'i',
    category: 'base',
    rowGroup: 'vowels',
    mnemonic: 'Two Eels swimming side by side',
    exampleWord: '犬',
    exampleReading: 'いぬ (inu)',
    exampleMeaning: 'dog',
    orderIndex: 2,
  },
  {
    character: 'う',
    romaji: 'u',
    category: 'base',
    rowGroup: 'vowels',
    mnemonic: 'A singer leaning forward saying Ooh',
    exampleWord: '海',
    exampleReading: 'うみ (umi)',
    exampleMeaning: 'sea / ocean',
    orderIndex: 3,
  },
  {
    character: 'え',
    romaji: 'e',
    category: 'base',
    rowGroup: 'vowels',
    mnemonic: 'An Energetic ninja running',
    exampleWord: '駅',
    exampleReading: 'えき (eki)',
    exampleMeaning: 'train station',
    orderIndex: 4,
  },
  {
    character: 'お',
    romaji: 'o',
    category: 'base',
    rowGroup: 'vowels',
    mnemonic: 'A golfer saying On the green!',
    exampleWord: 'お茶',
    exampleReading: 'おちゃ (ocha)',
    exampleMeaning: 'green tea',
    orderIndex: 5,
  },

  // K-row
  {
    character: 'か',
    romaji: 'ka',
    category: 'base',
    rowGroup: 'k-row',
    mnemonic: "A bird's beak opening wide to caw",
    exampleWord: '傘',
    exampleReading: 'かさ (kasa)',
    exampleMeaning: 'umbrella',
    orderIndex: 6,
  },
  {
    character: 'き',
    romaji: 'ki',
    category: 'base',
    rowGroup: 'k-row',
    mnemonic: 'Looks like an old-fashioned Key',
    exampleWord: '木',
    exampleReading: 'き (ki)',
    exampleMeaning: 'tree',
    orderIndex: 7,
  },
  {
    character: 'く',
    romaji: 'ku',
    category: 'base',
    rowGroup: 'k-row',
    mnemonic: 'The beak of a Cuckoo bird',
    exampleWord: '車',
    exampleReading: 'くるま (kuruma)',
    exampleMeaning: 'car',
    orderIndex: 8,
  },
  {
    character: 'け',
    romaji: 'ke',
    category: 'base',
    rowGroup: 'k-row',
    mnemonic: 'Looks like a wooden Keg of tea',
    exampleWord: '今朝',
    exampleReading: 'けさ (kesa)',
    exampleMeaning: 'this morning',
    orderIndex: 9,
  },
  {
    character: 'こ',
    romaji: 'ko',
    category: 'base',
    rowGroup: 'k-row',
    mnemonic: 'Two Koi fish swimming in a circle',
    exampleWord: '声',
    exampleReading: 'こえ (koe)',
    exampleMeaning: 'voice',
    orderIndex: 10,
  },

  // S-row
  {
    character: 'さ',
    romaji: 'sa',
    category: 'base',
    rowGroup: 's-row',
    mnemonic: 'A Samurai sword slicing downward',
    exampleWord: '魚',
    exampleReading: 'さかな (sakana)',
    exampleMeaning: 'fish',
    orderIndex: 11,
  },
  {
    character: 'し',
    romaji: 'shi',
    category: 'base',
    rowGroup: 's-row',
    mnemonic: 'A fishing hook caught in the sea',
    exampleWord: '白い',
    exampleReading: 'しろい (shiroi)',
    exampleMeaning: 'white',
    orderIndex: 12,
  },
  {
    character: 'す',
    romaji: 'su',
    category: 'base',
    rowGroup: 's-row',
    mnemonic: 'Swirling noodles in hot ramen soup',
    exampleWord: '寿司',
    exampleReading: 'すし (sushi)',
    exampleMeaning: 'sushi',
    orderIndex: 13,
  },
  {
    character: 'せ',
    romaji: 'se',
    category: 'base',
    rowGroup: 's-row',
    mnemonic: 'Two people sitting on the Senate bench',
    exampleWord: '先生',
    exampleReading: 'せんせい (sensei)',
    exampleMeaning: 'teacher',
    orderIndex: 14,
  },
  {
    character: 'そ',
    romaji: 'so',
    category: 'base',
    rowGroup: 's-row',
    mnemonic: 'Zigzag stitching with sewing thread',
    exampleWord: '空',
    exampleReading: 'そら (sora)',
    exampleMeaning: 'sky',
    orderIndex: 15,
  },

  // T-row
  {
    character: 'た',
    romaji: 'ta',
    category: 'base',
    rowGroup: 't-row',
    mnemonic: "Looks like the letters 't' and 'a'",
    exampleWord: '食べる',
    exampleReading: 'たべる (taberu)',
    exampleMeaning: 'to eat',
    orderIndex: 16,
  },
  {
    character: 'ち',
    romaji: 'chi',
    category: 'base',
    rowGroup: 't-row',
    mnemonic: 'A cheerleader waving her pom-pom',
    exampleWord: '地下鉄',
    exampleReading: 'ちかてつ (chikatetsu)',
    exampleMeaning: 'subway',
    orderIndex: 17,
  },
  {
    character: 'つ',
    romaji: 'tsu',
    category: 'base',
    rowGroup: 't-row',
    mnemonic: 'A giant Tsunami wave curling over',
    exampleWord: '机',
    exampleReading: 'つくえ (tsukue)',
    exampleMeaning: 'desk',
    orderIndex: 18,
  },
  {
    character: 'て',
    romaji: 'te',
    category: 'base',
    rowGroup: 't-row',
    mnemonic: "A dog's wagging tail curved up",
    exampleWord: '手',
    exampleReading: 'て (te)',
    exampleMeaning: 'hand',
    orderIndex: 19,
  },
  {
    character: 'と',
    romaji: 'to',
    category: 'base',
    rowGroup: 't-row',
    mnemonic: "A tiny thorn stuck in someone's Toe",
    exampleWord: '友達',
    exampleReading: 'ともだち (tomodachi)',
    exampleMeaning: 'friend',
    orderIndex: 20,
  },

  // N-row
  {
    character: 'な',
    romaji: 'na',
    category: 'base',
    rowGroup: 'n-row',
    mnemonic: 'A Nun praying before a holy cross',
    exampleWord: '名前',
    exampleReading: 'なまえ (namae)',
    exampleMeaning: 'name',
    orderIndex: 21,
  },
  {
    character: 'に',
    romaji: 'ni',
    category: 'base',
    rowGroup: 'n-row',
    mnemonic: 'A sewing Needle next to thread lines',
    exampleWord: '日本',
    exampleReading: 'にほん (nihon)',
    exampleMeaning: 'Japan',
    orderIndex: 22,
  },
  {
    character: 'ぬ',
    romaji: 'nu',
    category: 'base',
    rowGroup: 'n-row',
    mnemonic: 'Chopsticks pulling up tangled Noodles',
    exampleWord: 'ぬいぐるみ',
    exampleReading: 'ぬいぐるみ (nuigurumi)',
    exampleMeaning: 'stuffed toy',
    orderIndex: 23,
  },
  {
    character: 'ね',
    romaji: 'ne',
    category: 'base',
    rowGroup: 'n-row',
    mnemonic: 'A cat (neko) curled with a loop tail',
    exampleWord: '猫',
    exampleReading: 'ねこ (neko)',
    exampleMeaning: 'cat',
    orderIndex: 24,
  },
  {
    character: 'の',
    romaji: 'no',
    category: 'base',
    rowGroup: 'n-row',
    mnemonic: 'A clean No-smoking circle sign',
    exampleWord: '飲み物',
    exampleReading: 'のみもの (nomimono)',
    exampleMeaning: 'beverage',
    orderIndex: 25,
  },

  // H-row
  {
    character: 'は',
    romaji: 'ha',
    category: 'base',
    rowGroup: 'h-row',
    mnemonic: 'A person standing wearing a big Hat',
    exampleWord: '花',
    exampleReading: 'はな (hana)',
    exampleMeaning: 'flower',
    orderIndex: 26,
  },
  {
    character: 'ひ',
    romaji: 'hi',
    category: 'base',
    rowGroup: 'h-row',
    mnemonic: 'A wide laughing mouth going He-he-he',
    exampleWord: '光',
    exampleReading: 'ひかり (hikari)',
    exampleMeaning: 'light',
    orderIndex: 27,
  },
  {
    character: 'ふ',
    romaji: 'fu',
    category: 'base',
    rowGroup: 'h-row',
    mnemonic: 'Mount Fuji with clouds drifting down',
    exampleWord: '冬',
    exampleReading: 'ふゆ (fuyu)',
    exampleMeaning: 'winter',
    orderIndex: 28,
  },
  {
    character: 'へ',
    romaji: 'he',
    category: 'base',
    rowGroup: 'h-row',
    mnemonic: 'An arrow pointing upward to Heaven',
    exampleWord: '部屋',
    exampleReading: 'へや (heya)',
    exampleMeaning: 'room',
    orderIndex: 29,
  },
  {
    character: 'ほ',
    romaji: 'ho',
    category: 'base',
    rowGroup: 'h-row',
    mnemonic: 'A horse wearing a tall hat',
    exampleWord: '本',
    exampleReading: 'ほん (hon)',
    exampleMeaning: 'book',
    orderIndex: 30,
  },

  // M-row
  {
    character: 'ま',
    romaji: 'ma',
    category: 'base',
    rowGroup: 'm-row',
    mnemonic: 'A magician wearing a mask',
    exampleWord: '町',
    exampleReading: 'まち (machi)',
    exampleMeaning: 'town / city',
    orderIndex: 31,
  },
  {
    character: 'み',
    romaji: 'mi',
    category: 'base',
    rowGroup: 'm-row',
    mnemonic: 'Looks like the number 21 (Me at 21)',
    exampleWord: '水',
    exampleReading: 'みず (mizu)',
    exampleMeaning: 'water',
    orderIndex: 32,
  },
  {
    character: 'む',
    romaji: 'mu',
    category: 'base',
    rowGroup: 'm-row',
    mnemonic: 'A cow saying MOO with horns',
    exampleWord: '虫',
    exampleReading: 'むし (mushi)',
    exampleMeaning: 'insect',
    orderIndex: 33,
  },
  {
    character: 'め',
    romaji: 'me',
    category: 'base',
    rowGroup: 'm-row',
    mnemonic: 'A bowl of noodles without the loop',
    exampleWord: '目',
    exampleReading: 'め (me)',
    exampleMeaning: 'eye',
    orderIndex: 34,
  },
  {
    character: 'も',
    romaji: 'mo',
    category: 'base',
    rowGroup: 'm-row',
    mnemonic: 'A fishing hook catching More fish',
    exampleWord: '森',
    exampleReading: 'もり (mori)',
    exampleMeaning: 'forest',
    orderIndex: 35,
  },

  // Y-row
  {
    character: 'や',
    romaji: 'ya',
    category: 'base',
    rowGroup: 'y-row',
    mnemonic: 'A Yak horn curving upward',
    exampleWord: '山',
    exampleReading: 'やま (yama)',
    exampleMeaning: 'mountain',
    orderIndex: 36,
  },
  {
    character: 'ゆ',
    romaji: 'yu',
    category: 'base',
    rowGroup: 'y-row',
    mnemonic: 'A unique curved fish hook',
    exampleWord: '雪',
    exampleReading: 'ゆき (yuki)',
    exampleMeaning: 'snow',
    orderIndex: 37,
  },
  {
    character: 'よ',
    romaji: 'yo',
    category: 'base',
    rowGroup: 'y-row',
    mnemonic: 'A toy Yo-yo hanging on a string',
    exampleWord: '夜',
    exampleReading: 'よる (yoru)',
    exampleMeaning: 'night',
    orderIndex: 38,
  },

  // R-row
  {
    character: 'ら',
    romaji: 'ra',
    category: 'base',
    rowGroup: 'r-row',
    mnemonic: 'A rabbit sitting with long ears',
    exampleWord: '来週',
    exampleReading: 'らいしゅう (raishuu)',
    exampleMeaning: 'next week',
    orderIndex: 39,
  },
  {
    character: 'り',
    romaji: 'ri',
    category: 'base',
    rowGroup: 'r-row',
    mnemonic: 'Two parallel River reeds swaying',
    exampleWord: '林檎',
    exampleReading: 'りんご (ringo)',
    exampleMeaning: 'apple',
    orderIndex: 40,
  },
  {
    character: 'る',
    romaji: 'ru',
    category: 'base',
    rowGroup: 'r-row',
    mnemonic: 'A cursive road with a looping Roundabout',
    exampleWord: '留学生',
    exampleReading: 'りゅうがくせい (ryuugakusei)',
    exampleMeaning: 'exchange student',
    orderIndex: 41,
  },
  {
    character: 'れ',
    romaji: 're',
    category: 'base',
    rowGroup: 'r-row',
    mnemonic: 'A resting runner catching his breath',
    exampleWord: '練習',
    exampleReading: 'れんしゅう (renshuu)',
    exampleMeaning: 'practice',
    orderIndex: 42,
  },
  {
    character: 'ろ',
    romaji: 'ro',
    category: 'base',
    rowGroup: 'r-row',
    mnemonic: 'A winding Road without the loop',
    exampleWord: '廊下',
    exampleReading: 'ろうか (rouka)',
    exampleMeaning: 'hallway',
    orderIndex: 43,
  },

  // W-row & N
  {
    character: 'わ',
    romaji: 'wa',
    category: 'base',
    rowGroup: 'w-row',
    mnemonic: 'A magic Wand waving with a swirl',
    exampleWord: '私',
    exampleReading: 'わたし (watashi)',
    exampleMeaning: 'I / me',
    orderIndex: 44,
  },
  {
    character: 'を',
    romaji: 'wo',
    category: 'base',
    rowGroup: 'w-row',
    mnemonic: 'A cheerleader jumping Whoa! (particle o)',
    exampleWord: '本を読む',
    exampleReading: 'ほんをよむ (hon o yomu)',
    exampleMeaning: 'read a book',
    orderIndex: 45,
  },
  {
    character: 'ん',
    romaji: 'n',
    category: 'base',
    rowGroup: 'n',
    mnemonic: "Looks like lowercase letter 'n'",
    exampleWord: '日本',
    exampleReading: 'にほん (nihon)',
    exampleMeaning: 'Japan',
    orderIndex: 46,
  },

  // --- DAKUTEN (20) ---
  {
    character: 'が',
    romaji: 'ga',
    category: 'dakuten',
    rowGroup: 'k-row',
    mnemonic: 'か with voice marks (tenten)',
    exampleWord: '学校',
    exampleReading: 'がっこう (gakkou)',
    exampleMeaning: 'school',
    orderIndex: 47,
  },
  {
    character: 'ぎ',
    romaji: 'gi',
    category: 'dakuten',
    rowGroup: 'k-row',
    mnemonic: 'き with voice marks',
    exampleWord: '銀行',
    exampleReading: 'ぎんこう (ginkou)',
    exampleMeaning: 'bank',
    orderIndex: 48,
  },
  {
    character: 'ぐ',
    romaji: 'gu',
    category: 'dakuten',
    rowGroup: 'k-row',
    mnemonic: 'く with voice marks',
    exampleWord: 'ぐらい',
    exampleReading: 'ぐらい (gurai)',
    exampleMeaning: 'approximately',
    orderIndex: 49,
  },
  {
    character: 'げ',
    romaji: 'ge',
    category: 'dakuten',
    rowGroup: 'k-row',
    mnemonic: 'け with voice marks',
    exampleWord: '元気',
    exampleReading: 'げんき (genki)',
    exampleMeaning: 'healthy / energetic',
    orderIndex: 50,
  },
  {
    character: 'ご',
    romaji: 'go',
    category: 'dakuten',
    rowGroup: 'k-row',
    mnemonic: 'こ with voice marks',
    exampleWord: '午後',
    exampleReading: 'ごご (gogo)',
    exampleMeaning: 'p.m. / afternoon',
    orderIndex: 51,
  },

  {
    character: 'ざ',
    romaji: 'za',
    category: 'dakuten',
    rowGroup: 's-row',
    mnemonic: 'さ with voice marks',
    exampleWord: '雑誌',
    exampleReading: 'ざっし (zasshi)',
    exampleMeaning: 'magazine',
    orderIndex: 52,
  },
  {
    character: 'じ',
    romaji: 'ji',
    category: 'dakuten',
    rowGroup: 's-row',
    mnemonic: 'し with voice marks',
    exampleWord: '時間',
    exampleReading: 'じかん (jikan)',
    exampleMeaning: 'time / hours',
    orderIndex: 53,
  },
  {
    character: 'ず',
    romaji: 'zu',
    category: 'dakuten',
    rowGroup: 's-row',
    mnemonic: 'す with voice marks',
    exampleWord: 'ずっと',
    exampleReading: 'ずっと (zutto)',
    exampleMeaning: 'all the time / by far',
    orderIndex: 54,
  },
  {
    character: 'ぜ',
    romaji: 'ze',
    category: 'dakuten',
    rowGroup: 's-row',
    mnemonic: 'せ with voice marks',
    exampleWord: '全然',
    exampleReading: 'ぜんぜん (zenzen)',
    exampleMeaning: 'not at all',
    orderIndex: 55,
  },
  {
    character: 'ぞ',
    romaji: 'zo',
    category: 'dakuten',
    rowGroup: 's-row',
    mnemonic: 'そ with voice marks',
    exampleWord: 'どうぞ',
    exampleReading: 'どうぞ (douzo)',
    exampleMeaning: 'please go ahead',
    orderIndex: 56,
  },

  {
    character: 'だ',
    romaji: 'da',
    category: 'dakuten',
    rowGroup: 't-row',
    mnemonic: 'た with voice marks',
    exampleWord: '大学',
    exampleReading: 'だいがく (daigaku)',
    exampleMeaning: 'university',
    orderIndex: 57,
  },
  {
    character: 'ぢ',
    romaji: 'ji',
    category: 'dakuten',
    rowGroup: 't-row',
    mnemonic: 'ち with voice marks',
    exampleWord: '鼻血',
    exampleReading: 'はなぢ (hanaji)',
    exampleMeaning: 'nosebleed',
    orderIndex: 58,
  },
  {
    character: 'づ',
    romaji: 'zu',
    category: 'dakuten',
    rowGroup: 't-row',
    mnemonic: 'つ with voice marks',
    exampleWord: '続く',
    exampleReading: 'つづく (tsuzuku)',
    exampleMeaning: 'to continue',
    orderIndex: 59,
  },
  {
    character: 'で',
    romaji: 'de',
    category: 'dakuten',
    rowGroup: 't-row',
    mnemonic: 'て with voice marks',
    exampleWord: '電車',
    exampleReading: 'でんしゃ (densha)',
    exampleMeaning: 'train',
    orderIndex: 60,
  },
  {
    character: 'ど',
    romaji: 'do',
    category: 'dakuten',
    rowGroup: 't-row',
    mnemonic: 'と with voice marks',
    exampleWord: 'どこ',
    exampleReading: 'どこ (doko)',
    exampleMeaning: 'where',
    orderIndex: 61,
  },

  {
    character: 'ば',
    romaji: 'ba',
    category: 'dakuten',
    rowGroup: 'h-row',
    mnemonic: 'は with voice marks',
    exampleWord: '場所',
    exampleReading: 'ばしょ (basho)',
    exampleMeaning: 'place',
    orderIndex: 62,
  },
  {
    character: 'び',
    romaji: 'bi',
    category: 'dakuten',
    rowGroup: 'h-row',
    mnemonic: 'ひ with voice marks',
    exampleWord: '病院',
    exampleReading: 'びょういん (byouin)',
    exampleMeaning: 'hospital',
    orderIndex: 63,
  },
  {
    character: 'ぶ',
    romaji: 'bu',
    category: 'dakuten',
    rowGroup: 'h-row',
    mnemonic: 'ふ with voice marks',
    exampleWord: '豚肉',
    exampleReading: 'ぶたにく (butaniku)',
    exampleMeaning: 'pork',
    orderIndex: 64,
  },
  {
    character: 'べ',
    romaji: 'be',
    category: 'dakuten',
    rowGroup: 'h-row',
    mnemonic: 'へ with voice marks',
    exampleWord: '便利',
    exampleReading: 'べんり (benri)',
    exampleMeaning: 'convenient',
    orderIndex: 65,
  },
  {
    character: 'ぼ',
    romaji: 'bo',
    category: 'dakuten',
    rowGroup: 'h-row',
    mnemonic: 'ほ with voice marks',
    exampleWord: '帽子',
    exampleReading: 'ぼうし (boushi)',
    exampleMeaning: 'hat',
    orderIndex: 66,
  },

  // --- HANDAKUTEN (5) ---
  {
    character: 'ぱ',
    romaji: 'pa',
    category: 'handakuten',
    rowGroup: 'h-row',
    mnemonic: 'は with small circle (maru)',
    exampleWord: 'パン',
    exampleReading: 'パン (pan)',
    exampleMeaning: 'bread',
    orderIndex: 67,
  },
  {
    character: 'ぴ',
    romaji: 'pi',
    category: 'handakuten',
    rowGroup: 'h-row',
    mnemonic: 'ひ with small circle (maru)',
    exampleWord: 'ピカピカ',
    exampleReading: 'ピカピカ (pikapika)',
    exampleMeaning: 'sparkling',
    orderIndex: 68,
  },
  {
    character: 'ぷ',
    romaji: 'pu',
    category: 'handakuten',
    rowGroup: 'h-row',
    mnemonic: 'ふ with small circle (maru)',
    exampleWord: '切符',
    exampleReading: 'きっぷ (kippu)',
    exampleMeaning: 'ticket',
    orderIndex: 69,
  },
  {
    character: 'ぺ',
    romaji: 'pe',
    category: 'handakuten',
    rowGroup: 'h-row',
    mnemonic: 'へ with small circle (maru)',
    exampleWord: 'ペン',
    exampleReading: 'ペン (pen)',
    exampleMeaning: 'pen',
    orderIndex: 70,
  },
  {
    character: 'ぽ',
    romaji: 'po',
    category: 'handakuten',
    rowGroup: 'h-row',
    mnemonic: 'ほ with small circle (maru)',
    exampleWord: 'ポスト',
    exampleReading: 'ポスト (posuto)',
    exampleMeaning: 'mailbox',
    orderIndex: 71,
  },

  // --- YŌON (36) ---
  {
    character: 'きゃ',
    romaji: 'kya',
    category: 'yoon',
    rowGroup: 'k-row',
    mnemonic: 'き + small や',
    exampleWord: '客',
    exampleReading: 'きゃく (kyaku)',
    exampleMeaning: 'guest / customer',
    orderIndex: 72,
  },
  {
    character: 'きゅ',
    romaji: 'kyu',
    category: 'yoon',
    rowGroup: 'k-row',
    mnemonic: 'き + small ゆ',
    exampleWord: '急行',
    exampleReading: 'きゅうこう (kyuukou)',
    exampleMeaning: 'express train',
    orderIndex: 73,
  },
  {
    character: 'きょ',
    romaji: 'kyo',
    category: 'yoon',
    rowGroup: 'k-row',
    mnemonic: 'き + small よ',
    exampleWord: '今日',
    exampleReading: 'きょう (kyou)',
    exampleMeaning: 'today',
    orderIndex: 74,
  },

  {
    character: 'しゃ',
    romaji: 'sha',
    category: 'yoon',
    rowGroup: 's-row',
    mnemonic: 'し + small や',
    exampleWord: '写真',
    exampleReading: 'しゃしん (shashin)',
    exampleMeaning: 'photo',
    orderIndex: 75,
  },
  {
    character: 'しゅ',
    romaji: 'shu',
    category: 'yoon',
    rowGroup: 's-row',
    mnemonic: 'し + small ゆ',
    exampleWord: '宿題',
    exampleReading: 'しゅくだい (shukudai)',
    exampleMeaning: 'homework',
    orderIndex: 76,
  },
  {
    character: 'しょ',
    romaji: 'sho',
    category: 'yoon',
    rowGroup: 's-row',
    mnemonic: 'し + small よ',
    exampleWord: '食堂',
    exampleReading: 'しょくどう (shokudou)',
    exampleMeaning: 'cafeteria',
    orderIndex: 77,
  },

  {
    character: 'ちゃ',
    romaji: 'cha',
    category: 'yoon',
    rowGroup: 't-row',
    mnemonic: 'ち + small や',
    exampleWord: 'お茶',
    exampleReading: 'おちゃ (ocha)',
    exampleMeaning: 'green tea',
    orderIndex: 78,
  },
  {
    character: 'ちゅ',
    romaji: 'chu',
    category: 'yoon',
    rowGroup: 't-row',
    mnemonic: 'ち + small ゆ',
    exampleWord: '中国',
    exampleReading: 'ちゅうごく (chuugoku)',
    exampleMeaning: 'China',
    orderIndex: 79,
  },
  {
    character: 'ちょ',
    romaji: 'cho',
    category: 'yoon',
    rowGroup: 't-row',
    mnemonic: 'ち + small よ',
    exampleWord: 'ちょっと',
    exampleReading: 'ちょっと (chotto)',
    exampleMeaning: 'a little bit',
    orderIndex: 80,
  },

  {
    character: 'にゃ',
    romaji: 'nya',
    category: 'yoon',
    rowGroup: 'n-row',
    mnemonic: 'に + small や',
    exampleWord: 'こんにゃく',
    exampleReading: 'こんにゃく (konnyaku)',
    exampleMeaning: 'konjac',
    orderIndex: 81,
  },
  {
    character: 'にゅ',
    romaji: 'nyu',
    category: 'yoon',
    rowGroup: 'n-row',
    mnemonic: 'に + small ゆ',
    exampleWord: '牛乳',
    exampleReading: 'ぎゅうにゅう (gyuunyuu)',
    exampleMeaning: "cow's milk",
    orderIndex: 82,
  },
  {
    character: 'にょ',
    romaji: 'nyo',
    category: 'yoon',
    rowGroup: 'n-row',
    mnemonic: 'に + small よ',
    exampleWord: '女房',
    exampleReading: 'にょうぼう (nyoubou)',
    exampleMeaning: 'wife',
    orderIndex: 83,
  },

  {
    character: 'ひゃ',
    romaji: 'hya',
    category: 'yoon',
    rowGroup: 'h-row',
    mnemonic: 'ひ + small や',
    exampleWord: '百',
    exampleReading: 'ひゃく (hyaku)',
    exampleMeaning: 'one hundred',
    orderIndex: 84,
  },
  {
    character: 'ひゅ',
    romaji: 'hyu',
    category: 'yoon',
    rowGroup: 'h-row',
    mnemonic: 'ひ + small ゆ',
    exampleWord: 'ヒュー',
    exampleReading: 'ひゅー (hyuu)',
    exampleMeaning: 'whistling wind',
    orderIndex: 85,
  },
  {
    character: 'ひょ',
    romaji: 'hyo',
    category: 'yoon',
    rowGroup: 'h-row',
    mnemonic: 'ひ + small よ',
    exampleWord: '評判',
    exampleReading: 'ひょうばん (hyouban)',
    exampleMeaning: 'reputation',
    orderIndex: 86,
  },

  {
    character: 'みゃ',
    romaji: 'mya',
    category: 'yoon',
    rowGroup: 'm-row',
    mnemonic: 'み + small や',
    exampleWord: '脈',
    exampleReading: 'みゃく (myaku)',
    exampleMeaning: 'pulse',
    orderIndex: 87,
  },
  {
    character: 'みゅ',
    romaji: 'myu',
    category: 'yoon',
    rowGroup: 'm-row',
    mnemonic: 'み + small ゆ',
    exampleWord: 'ミュージカル',
    exampleReading: 'みゅーじかる (myuujikaru)',
    exampleMeaning: 'musical',
    orderIndex: 88,
  },
  {
    character: 'みょ',
    romaji: 'myo',
    category: 'yoon',
    rowGroup: 'm-row',
    mnemonic: 'み + small よ',
    exampleWord: '名字',
    exampleReading: 'みょうじ (myouji)',
    exampleMeaning: 'surname',
    orderIndex: 89,
  },

  {
    character: 'りゃ',
    romaji: 'rya',
    category: 'yoon',
    rowGroup: 'r-row',
    mnemonic: 'り + small や',
    exampleWord: '略',
    exampleReading: 'りゃく (ryaku)',
    exampleMeaning: 'abbreviation',
    orderIndex: 90,
  },
  {
    character: 'りゅ',
    romaji: 'ryu',
    category: 'yoon',
    rowGroup: 'r-row',
    mnemonic: 'り + small ゆ',
    exampleWord: '留学生',
    exampleReading: 'りゅうがくせい (ryuugakusei)',
    exampleMeaning: 'international student',
    orderIndex: 91,
  },
  {
    character: 'りょ',
    romaji: 'ryo',
    category: 'yoon',
    rowGroup: 'r-row',
    mnemonic: 'り + small よ',
    exampleWord: '旅行',
    exampleReading: 'りょこう (ryokou)',
    exampleMeaning: 'travel / trip',
    orderIndex: 92,
  },

  {
    character: 'ぎゃ',
    romaji: 'gya',
    category: 'yoon',
    rowGroup: 'k-row',
    mnemonic: 'ぎ + small や',
    exampleWord: 'ギャップ',
    exampleReading: 'ぎゃっぷ (gyappu)',
    exampleMeaning: 'gap',
    orderIndex: 93,
  },
  {
    character: 'ぎゅ',
    romaji: 'gyu',
    category: 'yoon',
    rowGroup: 'k-row',
    mnemonic: 'ぎ + small ゆ',
    exampleWord: '牛肉',
    exampleReading: 'ぎゅうにく (gyuuniku)',
    exampleMeaning: 'beef',
    orderIndex: 94,
  },
  {
    character: 'ぎょ',
    romaji: 'gyo',
    category: 'yoon',
    rowGroup: 'k-row',
    mnemonic: 'ぎ + small よ',
    exampleWord: '金魚',
    exampleReading: 'きんぎょ (kingyo)',
    exampleMeaning: 'goldfish',
    orderIndex: 95,
  },

  {
    character: 'じゃ',
    romaji: 'ja',
    category: 'yoon',
    rowGroup: 's-row',
    mnemonic: 'じ + small や',
    exampleWord: 'じゃあ',
    exampleReading: 'じゃあ (jaa)',
    exampleMeaning: 'well then',
    orderIndex: 96,
  },
  {
    character: 'じゅ',
    romaji: 'ju',
    category: 'yoon',
    rowGroup: 's-row',
    mnemonic: 'じ + small ゆ',
    exampleWord: '授業',
    exampleReading: 'じゅぎょう (jugyou)',
    exampleMeaning: 'class / lesson',
    orderIndex: 97,
  },
  {
    character: 'じょ',
    romaji: 'jo',
    category: 'yoon',
    rowGroup: 's-row',
    mnemonic: 'じ + small よ',
    exampleWord: '上手',
    exampleReading: 'じょうず (jouzu)',
    exampleMeaning: 'skillful',
    orderIndex: 98,
  },

  {
    character: 'びゃ',
    romaji: 'bya',
    category: 'yoon',
    rowGroup: 'h-row',
    mnemonic: 'び + small や',
    exampleWord: '白夜',
    exampleReading: 'びゃくや (byakuya)',
    exampleMeaning: 'white night',
    orderIndex: 99,
  },
  {
    character: 'びゅ',
    romaji: 'byu',
    category: 'yoon',
    rowGroup: 'h-row',
    mnemonic: 'び + small ゆ',
    exampleWord: 'ビュー',
    exampleReading: 'びゅー (byuu)',
    exampleMeaning: 'view',
    orderIndex: 100,
  },
  {
    character: 'びょ',
    romaji: 'byo',
    category: 'yoon',
    rowGroup: 'h-row',
    mnemonic: 'び + small よ',
    exampleWord: '病気',
    exampleReading: 'びょうき (byouki)',
    exampleMeaning: 'illness / sickness',
    orderIndex: 101,
  },

  {
    character: 'ぴゃ',
    romaji: 'pya',
    category: 'yoon',
    rowGroup: 'h-row',
    mnemonic: 'ぴ + small や',
    exampleWord: 'ハッピー',
    exampleReading: 'はっぴゃく (happyaku)',
    exampleMeaning: 'eight hundred',
    orderIndex: 102,
  },
  {
    character: 'ぴゅ',
    romaji: 'pyu',
    category: 'yoon',
    rowGroup: 'h-row',
    mnemonic: 'ぴ + small ゆ',
    exampleWord: 'ピュー',
    exampleReading: 'ぴゅー (pyuu)',
    exampleMeaning: 'pew sound',
    orderIndex: 103,
  },
  {
    character: 'ぴょ',
    romaji: 'pyo',
    category: 'yoon',
    rowGroup: 'h-row',
    mnemonic: 'ぴ + small よ',
    exampleWord: 'ひょっこり',
    exampleReading: 'ぴょんぴょん (pyonpyon)',
    exampleMeaning: 'hopping',
    orderIndex: 104,
  },
];
