export interface VocabSeedItem {
  lessonNumber: number;
  word: string;
  reading: string;
  romaji: string;
  meaning: string;
  partOfSpeech: 'noun' | 'pronoun' | 'verb' | 'adjective' | 'particle' | 'expression' | 'suffix';
  imageUrl: string;
  exampleSentence: string;
  exampleReading: string;
  exampleMeaning: string;
  orderIndex: number;
}

export const VOCAB_DATA: VocabSeedItem[] = [
  // ==========================================
  // LESSON 1: Self-Introductions & Nationalities
  // ==========================================
  {
    lessonNumber: 1,
    word: '私',
    reading: 'わたし',
    romaji: 'watashi',
    meaning: 'I, me',
    partOfSpeech: 'pronoun',
    imageUrl: '👤',
    exampleSentence: '私はケンです。',
    exampleReading: 'わたしはけんです。',
    exampleMeaning: 'I am Ken.',
    orderIndex: 1,
  },
  {
    lessonNumber: 1,
    word: 'あなた',
    reading: 'あなた',
    romaji: 'anata',
    meaning: 'you',
    partOfSpeech: 'pronoun',
    imageUrl: '👉',
    exampleSentence: 'あなたは学生ですか。',
    exampleReading: 'あなたはがくせいですか。',
    exampleMeaning: 'Are you a student?',
    orderIndex: 2,
  },
  {
    lessonNumber: 1,
    word: 'あの人',
    reading: 'あのひと',
    romaji: 'ano hito',
    meaning: 'that person',
    partOfSpeech: 'noun',
    imageUrl: '🚶',
    exampleSentence: 'あの人は先生です。',
    exampleReading: 'あのひとはせんせいです。',
    exampleMeaning: 'That person is a teacher.',
    orderIndex: 3,
  },
  {
    lessonNumber: 1,
    word: '先生',
    reading: 'せんせい',
    romaji: 'sensei',
    meaning: 'teacher, instructor',
    partOfSpeech: 'noun',
    imageUrl: '👩‍🏫',
    exampleSentence: '田中先生は日本人です。',
    exampleReading: 'たなかせんせいはにほんじんです。',
    exampleMeaning: 'Teacher Tanaka is Japanese.',
    orderIndex: 4,
  },
  {
    lessonNumber: 1,
    word: '学生',
    reading: 'がくせい',
    romaji: 'gakusei',
    meaning: 'student',
    partOfSpeech: 'noun',
    imageUrl: '🎓',
    exampleSentence: 'マリアさんは学生です。',
    exampleReading: 'まりあさんはがくせいです。',
    exampleMeaning: 'Maria is a student.',
    orderIndex: 5,
  },
  {
    lessonNumber: 1,
    word: '会社員',
    reading: 'かいしゃいん',
    romaji: 'kaishain',
    meaning: 'company employee',
    partOfSpeech: 'noun',
    imageUrl: '💼',
    exampleSentence: '父は会社員です。',
    exampleReading: 'ちははかいしゃいんです。',
    exampleMeaning: 'My father is a company employee.',
    orderIndex: 6,
  },
  {
    lessonNumber: 1,
    word: '医者',
    reading: 'いしゃ',
    romaji: 'isha',
    meaning: 'medical doctor',
    partOfSpeech: 'noun',
    imageUrl: '🩺',
    exampleSentence: '兄は医者です。',
    exampleReading: 'あにはいしゃです。',
    exampleMeaning: 'My older brother is a doctor.',
    orderIndex: 7,
  },
  {
    lessonNumber: 1,
    word: '日本',
    reading: 'にほん',
    romaji: 'nihon',
    meaning: 'Japan',
    partOfSpeech: 'noun',
    imageUrl: '🗾',
    exampleSentence: 'ここは日本です。',
    exampleReading: 'ここはにほんです。',
    exampleMeaning: 'This is Japan.',
    orderIndex: 8,
  },
  {
    lessonNumber: 1,
    word: 'アメリカ',
    reading: 'あめりか',
    romaji: 'amerika',
    meaning: 'USA, America',
    partOfSpeech: 'noun',
    imageUrl: '🗽',
    exampleSentence: 'ジョンさんはアメリカ人です。',
    exampleReading: 'じょんさんはあめりかじんです。',
    exampleMeaning: 'John is an American.',
    orderIndex: 9,
  },
  {
    lessonNumber: 1,
    word: '〜人',
    reading: '〜じん',
    romaji: 'jin',
    meaning: 'person of [nationality]',
    partOfSpeech: 'suffix',
    imageUrl: '🌐',
    exampleSentence: 'アンさんはフランス人です。',
    exampleReading: 'あんさんはふらんすじんです。',
    exampleMeaning: 'Ann is French.',
    orderIndex: 10,
  },
  {
    lessonNumber: 1,
    word: '初めまして',
    reading: 'はじめまして',
    romaji: 'hajimemashite',
    meaning: 'Nice to meet you (first greeting)',
    partOfSpeech: 'expression',
    imageUrl: '🤝',
    exampleSentence: '初めまして、ケンです。',
    exampleReading: 'はじめまして、けんです。',
    exampleMeaning: 'Nice to meet you, I am Ken.',
    orderIndex: 11,
  },
  {
    lessonNumber: 1,
    word: 'どうぞよろしく',
    reading: 'どうぞよろしく',
    romaji: 'douzo yoroshiku',
    meaning: 'Pleased to meet you / treat me well',
    partOfSpeech: 'expression',
    imageUrl: '🙇',
    exampleSentence: 'どうぞよろしくお願いします。',
    exampleReading: 'どうぞよろしくおねがいします。',
    exampleMeaning: 'Pleased to meet you.',
    orderIndex: 12,
  },

  // ==========================================
  // LESSON 2: Demonstratives & Everyday Objects
  // ==========================================
  {
    lessonNumber: 2,
    word: 'これ',
    reading: 'これ',
    romaji: 'kore',
    meaning: 'this (near speaker)',
    partOfSpeech: 'pronoun',
    imageUrl: '👇',
    exampleSentence: 'これは本です。',
    exampleReading: 'これはほんです。',
    exampleMeaning: 'This is a book.',
    orderIndex: 1,
  },
  {
    lessonNumber: 2,
    word: 'それ',
    reading: 'それ',
    romaji: 'sore',
    meaning: 'that (near listener)',
    partOfSpeech: 'pronoun',
    imageUrl: '👉',
    exampleSentence: 'それは辞書ですか。',
    exampleReading: 'それはじしょですか。',
    exampleMeaning: 'Is that a dictionary?',
    orderIndex: 2,
  },
  {
    lessonNumber: 2,
    word: 'あれ',
    reading: 'あれ',
    romaji: 'are',
    meaning: 'that over there (far from both)',
    partOfSpeech: 'pronoun',
    imageUrl: '👆',
    exampleSentence: 'あれは私の車です。',
    exampleReading: 'あれはわたしのくるまです。',
    exampleMeaning: 'That over there is my car.',
    orderIndex: 3,
  },
  {
    lessonNumber: 2,
    word: '本',
    reading: 'ほん',
    romaji: 'hon',
    meaning: 'book',
    partOfSpeech: 'noun',
    imageUrl: '📖',
    exampleSentence: 'これは日本語の本です。',
    exampleReading: 'これはにほんごのほんです。',
    exampleMeaning: 'This is a Japanese book.',
    orderIndex: 4,
  },
  {
    lessonNumber: 2,
    word: '辞書',
    reading: 'じしょ',
    romaji: 'jisho',
    meaning: 'dictionary',
    partOfSpeech: 'noun',
    imageUrl: '📚',
    exampleSentence: '辞書は机の上にあります。',
    exampleReading: 'じしょはつくえのうえにあります。',
    exampleMeaning: 'The dictionary is on the desk.',
    orderIndex: 5,
  },
  {
    lessonNumber: 2,
    word: '傘',
    reading: 'かさ',
    romaji: 'kasa',
    meaning: 'umbrella',
    partOfSpeech: 'noun',
    imageUrl: '☂️',
    exampleSentence: 'この傘は私のです。',
    exampleReading: 'このかさはわたしのです。',
    exampleMeaning: 'This umbrella is mine.',
    orderIndex: 6,
  },
  {
    lessonNumber: 2,
    word: '車',
    reading: 'くるま',
    romaji: 'kuruma',
    meaning: 'car, automobile',
    partOfSpeech: 'noun',
    imageUrl: '🚗',
    exampleSentence: 'あの車は先生の車です。',
    exampleReading: 'あのくるまはせんせいのくるまです。',
    exampleMeaning: "That car over there is the teacher's car.",
    orderIndex: 7,
  },
  {
    lessonNumber: 2,
    word: '誰',
    reading: 'だれ',
    romaji: 'dare',
    meaning: 'who',
    partOfSpeech: 'pronoun',
    imageUrl: '❓',
    exampleSentence: 'あの人は誰ですか。',
    exampleReading: 'あのひとはだれですか。',
    exampleMeaning: 'Who is that person?',
    orderIndex: 8,
  },
  {
    lessonNumber: 2,
    word: '何',
    reading: 'なん / なに',
    romaji: 'nan / nani',
    meaning: 'what',
    partOfSpeech: 'pronoun',
    imageUrl: '🤔',
    exampleSentence: 'これは何ですか。',
    exampleReading: 'これはなんですか。',
    exampleMeaning: 'What is this?',
    orderIndex: 9,
  },

  // ==========================================
  // LESSON 3: Locations & Facilities
  // ==========================================
  {
    lessonNumber: 3,
    word: 'ここ',
    reading: 'ここ',
    romaji: 'koko',
    meaning: 'here, this place',
    partOfSpeech: 'pronoun',
    imageUrl: '📍',
    exampleSentence: 'ここは教室です。',
    exampleReading: 'ここはきょうしつです。',
    exampleMeaning: 'Here is the classroom.',
    orderIndex: 1,
  },
  {
    lessonNumber: 3,
    word: '教室',
    reading: 'きょうしつ',
    romaji: 'kyoushitsu',
    meaning: 'classroom',
    partOfSpeech: 'noun',
    imageUrl: '🏫',
    exampleSentence: '学生は教室にいます。',
    exampleReading: 'がくせいはきょうしつにいます。',
    exampleMeaning: 'The student is in the classroom.',
    orderIndex: 2,
  },
  {
    lessonNumber: 3,
    word: '食堂',
    reading: 'しょくどう',
    romaji: 'shokudou',
    meaning: 'dining hall, cafeteria',
    partOfSpeech: 'noun',
    imageUrl: '🍽️',
    exampleSentence: '食堂はあそこです。',
    exampleReading: 'しょくどうはあそこです。',
    exampleMeaning: 'The dining hall is over there.',
    orderIndex: 3,
  },
  {
    lessonNumber: 3,
    word: '駅',
    reading: 'えき',
    romaji: 'eki',
    meaning: 'train station',
    partOfSpeech: 'noun',
    imageUrl: '🚉',
    exampleSentence: '駅はどこですか。',
    exampleReading: 'えきはどこですか。',
    exampleMeaning: 'Where is the train station?',
    orderIndex: 4,
  },
  {
    lessonNumber: 3,
    word: '家',
    reading: 'うち',
    romaji: 'uchi',
    meaning: 'home, house',
    partOfSpeech: 'noun',
    imageUrl: '🏡',
    exampleSentence: '私のうちは東京です。',
    exampleReading: 'わたしのうちはとうきょうです。',
    exampleMeaning: 'My home is in Tokyo.',
    orderIndex: 5,
  },
  {
    lessonNumber: 3,
    word: 'いくら',
    reading: 'いくら',
    romaji: 'ikura',
    meaning: 'how much (price)',
    partOfSpeech: 'pronoun',
    imageUrl: '💰',
    exampleSentence: 'この本はいくらですか。',
    exampleReading: 'このほんはいくらですか。',
    exampleMeaning: 'How much is this book?',
    orderIndex: 6,
  },

  // ==========================================
  // LESSON 4: Time & Daily Routines
  // ==========================================
  {
    lessonNumber: 4,
    word: '今',
    reading: 'いま',
    romaji: 'ima',
    meaning: 'now',
    partOfSpeech: 'noun',
    imageUrl: '⏰',
    exampleSentence: '今何時ですか。',
    exampleReading: 'いまなんじですか。',
    exampleMeaning: 'What time is it now?',
    orderIndex: 1,
  },
  {
    lessonNumber: 4,
    word: '今日',
    reading: 'きょう',
    romaji: 'kyou',
    meaning: 'today',
    partOfSpeech: 'noun',
    imageUrl: '📅',
    exampleSentence: '今日は月曜日です。',
    exampleReading: 'きょうはげつようびです。',
    exampleMeaning: 'Today is Monday.',
    orderIndex: 2,
  },
  {
    lessonNumber: 4,
    word: '起きます',
    reading: 'おきます',
    romaji: 'okimasu',
    meaning: 'wake up, get up',
    partOfSpeech: 'verb',
    imageUrl: '🌅',
    exampleSentence: '毎朝6時に起きます。',
    exampleReading: 'まいあさろくじにおきます。',
    exampleMeaning: 'I wake up at 6:00 every morning.',
    orderIndex: 3,
  },
  {
    lessonNumber: 4,
    word: '寝ます',
    reading: 'ねます',
    romaji: 'nemasu',
    meaning: 'sleep, go to bed',
    partOfSpeech: 'verb',
    imageUrl: '🛌',
    exampleSentence: '夜11時に寝ます。',
    exampleReading: 'よるじゅういちじにねます。',
    exampleMeaning: 'I go to sleep at 11:00 at night.',
    orderIndex: 4,
  },
  {
    lessonNumber: 4,
    word: '働きます',
    reading: 'はたらきます',
    romaji: 'hatarakimasu',
    meaning: 'work',
    partOfSpeech: 'verb',
    imageUrl: '🧑‍💻',
    exampleSentence: '月曜日から金曜日まで働きます。',
    exampleReading: 'げつようびからきんようびまではたらきます。',
    exampleMeaning: 'I work from Monday to Friday.',
    orderIndex: 5,
  },
  {
    lessonNumber: 4,
    word: '勉強します',
    reading: 'べんきょうします',
    romaji: 'benkyoushimasu',
    meaning: 'study',
    partOfSpeech: 'verb',
    imageUrl: '📝',
    exampleSentence: '毎晩日本語を勉強します。',
    exampleReading: 'まいばんにほんごをべんきょうします。',
    exampleMeaning: 'I study Japanese every evening.',
    orderIndex: 6,
  },

  // ==========================================
  // LESSON 5: Transit & Motion Verbs
  // ==========================================
  {
    lessonNumber: 5,
    word: '行きます',
    reading: 'いきます',
    romaji: 'ikimasu',
    meaning: 'go',
    partOfSpeech: 'verb',
    imageUrl: '🚶‍♂️',
    exampleSentence: '明日東京へ行きます。',
    exampleReading: 'あしたとうきょうへいきます。',
    exampleMeaning: 'I will go to Tokyo tomorrow.',
    orderIndex: 1,
  },
  {
    lessonNumber: 5,
    word: '来ます',
    reading: 'きます',
    romaji: 'kimasu',
    meaning: 'come',
    partOfSpeech: 'verb',
    imageUrl: '🛬',
    exampleSentence: '友だちが日本へ来ます。',
    exampleReading: 'ともだちがにほんへきます。',
    exampleMeaning: 'A friend is coming to Japan.',
    orderIndex: 2,
  },
  {
    lessonNumber: 5,
    word: '帰ります',
    reading: 'かえります',
    romaji: 'kaerimasu',
    meaning: 'return, go home',
    partOfSpeech: 'verb',
    imageUrl: '🏠',
    exampleSentence: '7時にうちへ帰ります。',
    exampleReading: 'しちじにうちへかえります。',
    exampleMeaning: 'I go home at 7:00.',
    orderIndex: 3,
  },
  {
    lessonNumber: 5,
    word: '電車',
    reading: 'でんしゃ',
    romaji: 'densha',
    meaning: 'electric train',
    partOfSpeech: 'noun',
    imageUrl: '🚆',
    exampleSentence: '電車で会社へ行きます。',
    exampleReading: 'でんしゃでかいしゃへいきます。',
    exampleMeaning: 'I go to work by train.',
    orderIndex: 4,
  },
  {
    lessonNumber: 5,
    word: '自転車',
    reading: 'じてんしゃ',
    romaji: 'jitensha',
    meaning: 'bicycle',
    partOfSpeech: 'noun',
    imageUrl: '🚲',
    exampleSentence: '自転車で駅へ行きます。',
    exampleReading: 'じてんしゃでえきへいきます。',
    exampleMeaning: 'I go to the station by bicycle.',
    orderIndex: 5,
  },
  {
    lessonNumber: 5,
    word: '友達',
    reading: 'ともだち',
    romaji: 'tomodachi',
    meaning: 'friend',
    partOfSpeech: 'noun',
    imageUrl: '🧑‍🤝‍🧑',
    exampleSentence: '友達と映画へ行きます。',
    exampleReading: 'ともだちとえいがへいきます。',
    exampleMeaning: 'I will go to a movie with a friend.',
    orderIndex: 6,
  },
];
